# Model
model:
# "t5-v1_1-small", "t5-v1_1-large", "gpt2"
  model_name: "ai-forever/FRED-T5-1.7B"
  tokenizer_name: "ai-forever/FRED-T5-1.7B"
  local_path: 'INIT'
  use_local: False
  path_save_model: ""
  input_max_length: 20
  target_max_length: 750
  total_samples: 1000000
  batch_size: 4
  predict_param:
    do_sample: True
    num_beams: 1
    temperature: 1
    top_p: 0.9
    top_k: 50
    max_length: 750

result:
  launch_description: "T5_prediction"
  path_to_save_result: "/home/d.maximov/data"
  save_examples: True
  number_examples_batch: 2
  gpt_postprocessing: True

# Dataset
dataset:
  # file_path: 'D:\\projects_andrey\\datasets_made\\fulldocs_txt.txt'
  save_dir: '/home/d.maximov/data'
  # full_data - с сайта, part_data - размеченная с hugging face
  dataset_name: "made_valid_data"
  block_size: 128
  mlm: False

  # Gdown помойка, надеюсь они починять folder_download
  gdrive_dict:
    full_data: https://drive.google.com/uc?id=1NCjkrgzKsOpwxHUMW-x0KQzSZbpm6g9P
    part_data:
      train: https://drive.google.com/uc?id=1x_Sho7xYqsJPvB8zDZWudSO4WsifhJfs
      test: https://drive.google.com/uc?id=1R-k_Osj7NFi1rEvx0citRIbzXT7IzIAc
      val: https://drive.google.com/uc?id=1RBoqgf2d5cGUNne6F7ZWZd4GUwQpSqjZ

